import { useEffect, useMemo, useState } from "react";
import { calculateIncomeAnalysis } from "../../lib/income-analysis/incomeCalculator";
import { buildIncomeWhatsAppMessage } from "../../lib/income-analysis/incomeMessageBuilder";
import { generateIncomePdf } from "../../lib/income-analysis/incomePdfGenerator";
import { BankTransaction, IncomeAnalysisForm, IncomeAnalysisState, IncomeSimulationPrefill } from "../../types/incomeAnalysis";
import { IncomeAnalysisHeader } from "./IncomeAnalysisHeader";
import { IncomeAnalysisSetup } from "./IncomeAnalysisSetup";
import { TransactionEntryForm } from "./TransactionEntryForm";
import { TransactionImport } from "./TransactionImport";
import { TransactionTable } from "./TransactionTable";
import { MonthlyIncomeSummary } from "./MonthlyIncomeSummary";
import { IncomeCharts } from "./IncomeCharts";
import { PayerRecurrenceTable } from "./PayerRecurrenceTable";
import { IncomeResultPanel } from "./IncomeResultPanel";

const STATE_KEY = "goodcredit_income_analysis_state"; const PREF_KEY = "goodcredit_income_analysis_preferences"; const SIM_KEY = "goodcredit_income_simulation_prefill";
const currentMonth = new Date().toISOString().slice(0, 7); const initialForm: IncomeAnalysisForm = { clientName: "", incomeProfile: "", participantCount: "1", bank: "Caixa", accountCount: 1, periodStart: currentMonth, periodEnd: currentMonth, analysisType: "SINGLE_ACCOUNT", declaredActivity: "", analystNotes: "", excludedCompetences: {} };
function loadState(): IncomeAnalysisState { try { const parsed = JSON.parse(localStorage.getItem(STATE_KEY) || "null"); return parsed?.version === 1 ? { ...parsed.data, doNotSave: Boolean(JSON.parse(localStorage.getItem(PREF_KEY) || "{}").doNotSave) } : { form: initialForm, transactions: [], doNotSave: false }; } catch { return { form: initialForm, transactions: [], doNotSave: false }; } }

export function IncomeAnalysisPage({ onSendToSimulation }: { onSendToSimulation: () => void }) {
  const [state, setState] = useState(loadState); const [notice, setNotice] = useState(""); const result = useMemo(() => calculateIncomeAnalysis(state.form, state.transactions), [state.form, state.transactions]);
  useEffect(() => { localStorage.setItem(PREF_KEY, JSON.stringify({ doNotSave: state.doNotSave })); if (state.doNotSave) { localStorage.removeItem(STATE_KEY); return; } localStorage.setItem(STATE_KEY, JSON.stringify({ version: 1, savedAt: new Date().toISOString(), data: { form: state.form, transactions: state.transactions, doNotSave: false } })); }, [state]);
  useEffect(() => { if (!state.doNotSave || !state.transactions.length) return; const handler = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [state.doNotSave, state.transactions.length]);
  function clear() { if (!window.confirm("Esta ação removerá todas as movimentações e classificações desta apuração.")) return; localStorage.removeItem(STATE_KEY); setState({ form: initialForm, transactions: [], doNotSave: state.doNotSave }); setNotice("Análise limpa."); }
  async function copy() { await navigator.clipboard.writeText(buildIncomeWhatsAppMessage(state.form, result)); setNotice("Resumo copiado para a área de transferência."); }
  function send() { const prefill: IncomeSimulationPrefill = { clientName: state.form.clientName, incomeProfile: state.form.incomeProfile, analyzedPeriod: { start: state.form.periodStart, end: state.form.periodEnd, months: result.monthCount }, averageIncome: result.averageIncome, medianIncome: result.medianIncome, totalConsidered: result.totalIncluded, pendingReviewAmount: result.totalReview, generatedAt: new Date().toISOString() }; localStorage.setItem(SIM_KEY, JSON.stringify(prefill)); onSendToSimulation(); }
  const formErrors = !state.form.clientName.trim() || !state.form.incomeProfile || !state.form.periodStart || !state.form.periodEnd || state.form.periodEnd < state.form.periodStart;
  return <div><IncomeAnalysisHeader onClear={clear} /><main className="mx-auto flex max-w-[1700px] flex-col gap-6 px-4 py-6 sm:px-6 xl:px-8">{notice && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}<label className="flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><input type="checkbox" className="mt-0.5" checked={state.doNotSave} onChange={(e) => setState({ ...state, doNotSave: e.target.checked })} /><span><strong>Não salvar esta análise no navegador.</strong> Os dados permanecerão apenas nesta sessão e serão apagados ao atualizar ou fechar.</span></label><IncomeAnalysisSetup form={state.form} onChange={(form) => setState({ ...state, form })} />{formErrors && <p className="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">Informe nome/processo, perfil e um período válido para concluir a apuração.</p>}<TransactionEntryForm onAdd={(transaction) => setState({ ...state, transactions: [...state.transactions, transaction] })} /><TransactionImport existing={state.transactions} analysisBank={state.form.bank} periodStart={state.form.periodStart} periodEnd={state.form.periodEnd} onImport={(transactions) => setState({ ...state, transactions })} /><div className="rounded-lg border border-goodblue-100 bg-goodblue-50 p-4 text-sm text-goodblue-800">Os arquivos e movimentações são processados localmente no navegador. Nenhum extrato é enviado pela ferramenta.</div><TransactionTable transactions={state.transactions} onChange={(transactions) => setState({ ...state, transactions })} /><MonthlyIncomeSummary form={state.form} result={result} onFormChange={(form) => setState({ ...state, form })} /><IncomeCharts result={result} /><PayerRecurrenceTable result={result} /><IncomeResultPanel form={state.form} result={result} onCopy={copy} onPdfSummary={() => generateIncomePdf(state.form, result, state.transactions, false)} onPdfDetailed={() => generateIncomePdf(state.form, result, state.transactions, true)} onSend={send} /></main></div>;
}
