import { FileDown, RefreshCcw, Send, TableProperties } from "lucide-react";
import type { AutomatedIncomeResult, NormalizedBankTransaction } from "../../types/statementAnalysis";
import { GoodCreditExplanation } from "./GoodCreditExplanation";
import { IncomeMonthlyResults } from "./IncomeMonthlyResults";
import { IncomeSummaryCards } from "./IncomeSummaryCards";
import { ReconciliationPanel } from "./ReconciliationPanel";

export function IncomeAnalysisResult({ result, onReview, onPdf, onSend, onReset }: { result: AutomatedIncomeResult; onReview: () => void; onPdf: () => void; onSend: () => void; onReset: () => void; onTransaction?: (transaction: NormalizedBankTransaction) => void }) {
  return <main className="mx-auto flex max-w-[1600px] flex-col gap-6 px-4 py-7 sm:px-6 xl:px-8"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-goodgreen-600">Análise concluída</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Resultado da Apuração de Renda</h1><p className="mt-2 text-sm text-slate-500">{result.files.length} arquivo(s), {new Set(result.files.map((file) => file.bank)).size} banco(s) e {result.months.length} competência(s) analisada(s).</p></div><div className="flex flex-wrap gap-2"><button type="button" className="btn-muted" onClick={onReset}><RefreshCcw className="h-4 w-4" /> Nova análise</button><button type="button" className="btn-secondary" onClick={onReview}><TableProperties className="h-4 w-4" /> Revisar movimentações</button><button type="button" className="btn-secondary" onClick={onPdf}><FileDown className="h-4 w-4" /> Gerar relatório</button><button type="button" className="btn-primary" disabled={!result.confirmedMonthlyIncome} onClick={onSend}><Send className="h-4 w-4" /> Enviar renda para Simulação</button></div></header>
  <IncomeSummaryCards result={result} />
  {(result.totalPending > 0 || result.reconciliationStatus === "DIVERGENCE") && <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">A análise possui {result.totalPending > 0 ? "valores pendentes" : ""}{result.totalPending > 0 && result.reconciliationStatus === "DIVERGENCE" ? " e " : ""}{result.reconciliationStatus === "DIVERGENCE" ? "divergência de conciliação" : ""}. Use a revisão avançada antes de concluir.</div>}
  <GoodCreditExplanation result={result} />
  <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><IncomeMonthlyResults result={result} /><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Concentração e recorrência</h2><p className="mt-1 text-xs text-slate-500">Indicador de apoio, sem reprovação automática.</p><div className="mt-4 space-y-3">{result.payerConcentration.slice(0, 6).map((payer) => <div key={payer.payer}><div className="flex justify-between gap-3 text-xs"><span className="truncate font-semibold">{payer.payer}</span><span>{(payer.share * 100).toFixed(1)}%</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-goodblue-500" style={{ width: `${Math.min(100, payer.share * 100)}%` }} /></div><p className="mt-1 text-[11px] text-slate-500">{payer.months} mês(es) · {payer.occurrences} recebimento(s)</p></div>)}{!result.payerConcentration.length && <p className="text-sm text-slate-500">Nenhum pagador confirmado.</p>}</div></section></div>
  <ReconciliationPanel files={result.files} />
  <p className="rounded-lg border border-slate-200 bg-white p-4 text-xs leading-5 text-slate-500">Indicador interno de apoio à análise. Não representa critério oficial de aprovação bancária.</p>
  </main>;
}
