import { Check, LoaderCircle, X } from "lucide-react";
import type { StatementFileRecord, StatementProcessingProgress } from "../../types/statementAnalysis";
import { PROCESSING_STEPS } from "../../lib/statement-analysis/statementPipeline";

export function StatementProcessing({ files, progress, onCancel }: { files: StatementFileRecord[]; progress: StatementProcessingProgress | null; onCancel: () => void }) {
  return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-goodblue-600">Processamento local</p><h1 className="mt-2 text-2xl font-bold text-slate-950">Analisando extratos</h1><p className="mt-2 text-sm text-slate-500">{progress?.fileName || "Preparando arquivos"}</p></div><button type="button" className="btn-muted" onClick={onCancel}><X className="h-4 w-4" /> Cancelar</button></div>
    <div className="mt-6 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-goodgreen-600 transition-all" style={{ width: `${progress?.percent || 1}%` }} /></div><div className="mt-2 flex justify-between text-xs font-semibold text-slate-500"><span>{progress?.stepLabel || "Validando arquivos"}</span><span>{progress?.percent || 0}%</span></div>
    {progress?.totalPages ? <p className="mt-2 text-sm font-semibold text-goodblue-700">Página {progress.currentPage || 1} de {progress.totalPages}</p> : null}
    <div className="mt-7 grid gap-2 sm:grid-cols-2">{PROCESSING_STEPS.map((step, index) => { const active = index === (progress?.step || 0); const done = index < (progress?.step || 0); return <div key={step} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active ? "bg-blue-50 font-bold text-goodblue-800" : done ? "text-emerald-700" : "text-slate-400"}`}>{done ? <Check className="h-4 w-4" /> : active ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <span className="h-4 w-4 rounded-full border border-slate-300" />} {step}</div>; })}</div>
    <div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-slate-200 p-4"><p className="text-xs text-slate-500">Arquivos</p><strong>{files.length}</strong></div><div className="rounded-lg border border-slate-200 p-4"><p className="text-xs text-slate-500">Concluídos</p><strong>{files.filter((file) => ["COMPLETED", "REVIEW_REQUIRED", "DIVERGENT"].includes(file.status)).length}</strong></div><div className="rounded-lg border border-slate-200 p-4"><p className="text-xs text-slate-500">Com alertas</p><strong>{files.filter((file) => ["REVIEW_REQUIRED", "DIVERGENT", "ERROR", "UNRECOGNIZED"].includes(file.status)).length}</strong></div></div>
    </section></main>;
}
