import { FileUp, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useRef, useState } from "react";
import type { RelatedPerson, StatementFileRecord } from "../../types/statementAnalysis";
import { StatementFileList } from "./StatementFileList";

export function StatementUpload({ clientName, files, relatedPeople, onClientName, onAddFiles, onRemoveFile, onRelatedPeople, onStart, onClear }: { clientName: string; files: StatementFileRecord[]; relatedPeople: RelatedPerson[]; onClientName: (value: string) => void; onAddFiles: (files: File[]) => void; onRemoveFile: (id: string) => void; onRelatedPeople: (value: RelatedPerson[]) => void; onStart: () => void; onClear: () => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const [dragging, setDragging] = useState(false); const [relatedName, setRelatedName] = useState(""); const [relationship, setRelationship] = useState("");
  const accept = ".pdf,.csv,.xlsx,.xls,application/pdf,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
  function addRelated() { if (!relatedName.trim()) return; onRelatedPeople([...relatedPeople, { id: `related-${Date.now()}`, name: relatedName.trim(), relationship: relationship.trim() || "Pessoa relacionada" }]); setRelatedName(""); setRelationship(""); }
  return <main className="mx-auto max-w-[1500px] px-4 py-7 sm:px-6 xl:px-8">
    <header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-goodgreen-600">GoodCredit Hub</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Apuração Automática de Renda</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Envie os extratos bancários para receber uma análise consolidada das entradas consideradas como renda.</p></header>
    <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
      <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(280px,0.7fr)]"><div><label className="text-sm font-bold text-slate-700">Cliente ou processo<input className="input-field mt-2" value={clientName} onChange={(event) => onClientName(event.target.value)} placeholder="Nome usado no relatório e na simulação" /></label>
        <div className={`mt-5 flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed p-6 text-center transition ${dragging ? "border-goodgreen-500 bg-emerald-50" : "border-slate-300 bg-slate-50 hover:border-goodblue-400 hover:bg-blue-50/40"}`} onClick={() => inputRef.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); onAddFiles([...event.dataTransfer.files]); }}><FileUp className="h-9 w-9 text-goodblue-600" /><h2 className="mt-4 text-lg font-bold text-slate-950">Arraste os extratos para esta área</h2><p className="mt-2 max-w-xl text-sm text-slate-500">PDF, CSV, XLSX ou XLS. Você pode combinar bancos, contas, participantes e competências.</p><button type="button" className="btn-secondary mt-5" onClick={(event) => { event.stopPropagation(); inputRef.current?.click(); }}><Plus className="h-4 w-4" /> Adicionar arquivos</button><input ref={inputRef} type="file" multiple accept={accept} className="hidden" onChange={(event) => { onAddFiles([...(event.target.files || [])]); event.target.value = ""; }} /></div>
      </div><aside className="rounded-lg border border-slate-200 bg-slate-50 p-5"><h2 className="font-bold text-slate-900">Pessoas relacionadas</h2><p className="mt-1 text-xs leading-5 text-slate-500">Cadastre apenas relações confirmadas. O sistema não presume parentesco pelo nome.</p><div className="mt-4 space-y-3"><input className="input-field" value={relatedName} onChange={(event) => setRelatedName(event.target.value)} placeholder="Nome da pessoa" /><input className="input-field" value={relationship} onChange={(event) => setRelationship(event.target.value)} placeholder="Relação: cônjuge, familiar..." /><button type="button" className="btn-muted w-full" onClick={addRelated}><Plus className="h-4 w-4" /> Adicionar pessoa</button></div><div className="mt-4 space-y-2">{relatedPeople.map((person) => <div key={person.id} className="flex items-center justify-between gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs"><span><strong>{person.name}</strong><br />{person.relationship}</span><button type="button" title="Remover" className="p-1 text-slate-400 hover:text-rose-700" onClick={() => onRelatedPeople(relatedPeople.filter((item) => item.id !== person.id))}><Trash2 className="h-4 w-4" /></button></div>)}</div></aside></div>
      <StatementFileList files={files} disabled={false} onRemove={onRemoveFile} />
      <div className="mt-5 flex flex-col gap-4 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="flex max-w-3xl items-start gap-2 text-xs leading-5 text-slate-500"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-goodgreen-600" />Os arquivos são processados localmente no navegador e não são enviados ou armazenados pela plataforma.</p><div className="flex gap-3"><button type="button" className="btn-muted" disabled={!files.length} onClick={onClear}>Limpar</button><button type="button" className="btn-primary" disabled={!files.length} onClick={onStart}>Iniciar análise</button></div></div>
    </section>
  </main>;
}
