import { useState } from "react";
import { FileText, Upload } from "lucide-react";
import { BankTransaction, CsvColumnMapping, CsvPreview } from "../../types/incomeAnalysis";
import { csvRowsToTransactions, parseCsvPreview } from "../../lib/income-analysis/csvParser";
import { flagPossibleDuplicates } from "../../lib/income-analysis/transactionClassifier";
import { CsvMappingModal } from "./CsvMappingModal";

const initialMapping: CsvColumnMapping = { date: "", description: "", amount: "", type: "", payer: "", account: "", competence: "" };
export function TransactionImport({ existing, onImport }: { existing: BankTransaction[]; onImport: (transactions: BankTransaction[]) => void }) {
  const [separator, setSeparator] = useState(";"); const [ignoreHeader, setIgnoreHeader] = useState(true); const [preview, setPreview] = useState<CsvPreview | null>(null); const [mapping, setMapping] = useState(initialMapping); const [paste, setPaste] = useState("");
  function openContent(content: string) { const next = parseCsvPreview(content, separator, ignoreHeader); setPreview(next); setMapping({ ...initialMapping, date: next.headers.find((h) => /data/i.test(h)) || "", description: next.headers.find((h) => /descr/i.test(h)) || "", amount: next.headers.find((h) => /valor/i.test(h)) || "", type: next.headers.find((h) => /tipo|natureza/i.test(h)) || "", payer: next.headers.find((h) => /pagador|origem/i.test(h)) || "", account: next.headers.find((h) => /conta/i.test(h)) || "", competence: next.headers.find((h) => /compet/i.test(h)) || "" }); }
  function fileChange(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => openContent(String(reader.result || "")); reader.readAsText(file, "UTF-8"); }
  function confirm() { if (!preview) return; onImport(flagPossibleDuplicates([...existing, ...csvRowsToTransactions(preview, mapping)])); setPreview(null); setPaste(""); }
  return <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-bold">Importar Movimentações</h2><p className="mt-1 text-sm text-slate-500">O arquivo é processado localmente e o original não é armazenado.</p><div className="mt-5 flex flex-wrap items-end gap-4"><label className="text-sm font-semibold">Separador<select className="mt-2 h-11 rounded-lg border border-slate-300 px-3" value={separator} onChange={(e) => setSeparator(e.target.value)}><option value=";">Ponto e vírgula</option><option value=",">Vírgula</option><option value={'\t'}>Tabulação</option></select></label><label className="flex h-11 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold"><input type="checkbox" checked={ignoreHeader} onChange={(e) => setIgnoreHeader(e.target.checked)} />Ignorar cabeçalho</label><label className="btn-secondary cursor-pointer"><Upload className="h-4 w-4" /> Selecionar CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={(e) => fileChange(e.target.files?.[0])} /></label><button type="button" className="btn-muted cursor-not-allowed opacity-60" disabled><FileText className="h-4 w-4" /> Importação de PDF — Em breve</button></div><label className="mt-5 block text-sm font-semibold">Ou cole dados estruturados<textarea className="mt-2 min-h-28 w-full rounded-lg border border-slate-300 p-3 font-mono text-xs" value={paste} onChange={(e) => setPaste(e.target.value)} placeholder="Data;Descrição;Valor;Tipo;Pagador;Conta" /></label><button type="button" className="btn-secondary mt-3" disabled={!paste.trim()} onClick={() => openContent(paste)}>Mapear dados colados</button>{preview && <CsvMappingModal preview={preview} mapping={mapping} onMapping={setMapping} onConfirm={confirm} onClose={() => setPreview(null)} />}</section>;
}
