import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { BankTransaction, IncomeAnalysisForm, IncomeAnalysisResult } from "../../types/incomeAnalysis";
import { formatCompetence, formatCurrencyBR, maskAccount } from "./formatters";
import { INCOME_ANALYSIS_RULES, INCOME_PROFILE_LABELS } from "./incomeRules";

async function loadLogo(): Promise<string | null> { try { const response = await fetch("/logo-goodcredit-hub.png"); if (!response.ok) return null; const blob = await response.blob(); return await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => resolve(null); reader.readAsDataURL(blob); }); } catch { return null; } }

export async function generateIncomePdf(form: IncomeAnalysisForm, result: IncomeAnalysisResult, transactions: BankTransaction[], detailed: boolean) {
  const pdf = new jsPDF({ unit: "mm", format: "a4" }); const margin = 14; let y = 14; const logo = await loadLogo(); if (logo) pdf.addImage(logo, "PNG", margin, y, 30, 24);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(17); pdf.setTextColor(15, 23, 42); pdf.text("Relatório de Apuração de Renda", margin, y + 30); pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); pdf.setTextColor(71, 85, 105); pdf.text(`Cliente/processo: ${form.clientName}`, margin, y + 38); pdf.text(`Perfil: ${form.incomeProfile ? INCOME_PROFILE_LABELS[form.incomeProfile] : "Não informado"}`, margin, y + 44); pdf.text(`Período: ${formatCompetence(form.periodStart)} a ${formatCompetence(form.periodEnd)} | Gerado em ${new Date().toLocaleDateString("pt-BR")}`, margin, y + 50); y += 60;
  const facts = [["Meses analisados", String(result.monthCount)], ["Total de entradas", formatCurrencyBR(result.totalEntries)], ["Total considerado", formatCurrencyBR(result.totalIncluded)], ["Total desconsiderado", formatCurrencyBR(result.totalExcluded)], ["Em revisão", formatCurrencyBR(result.totalReview)], ["Renda média", formatCurrencyBR(result.averageIncome)], ["Mediana", formatCurrencyBR(result.medianIncome)], ["Estabilidade", result.stabilityLabel]];
  facts.forEach(([label, value]) => { pdf.setFont("helvetica", "bold"); pdf.text(`${label}:`, margin, y); pdf.setFont("helvetica", "normal"); pdf.text(value, margin + 43, y); y += 6; });
  const chart = Array.from(document.querySelectorAll("h3")).find((heading) => heading.textContent === "Renda por mês")?.parentElement;
  if (chart) { const canvas = await html2canvas(chart, { scale: 1.5, backgroundColor: "#ffffff" }); const width = 182; const height = Math.min(68, canvas.height * width / canvas.width); if (y + height > 275) { pdf.addPage(); y = 15; } pdf.addImage(canvas.toDataURL("image/png"), "PNG", margin, y + 2, width, height); y += height + 8; }
  y += 3; pdf.setFont("helvetica", "bold"); pdf.text("Resultado mensal", margin, y); y += 6; pdf.setFont("helvetica", "normal");
  result.months.forEach((month) => { if (y > 275) { pdf.addPage(); y = 15; } pdf.text(`${formatCompetence(month.competence)} | entradas ${formatCurrencyBR(month.totalEntries)} | considerado ${formatCurrencyBR(month.totalIncluded)} | revisão ${formatCurrencyBR(month.totalReview)}`, margin, y); y += 5; });
  if (detailed) { y += 4; pdf.setFont("helvetica", "bold"); pdf.text("Movimentações detalhadas", margin, y); y += 6; pdf.setFont("helvetica", "normal"); transactions.slice(0, 80).forEach((item) => { if (y > 275) { pdf.addPage(); y = 15; } const classification = INCOME_ANALYSIS_RULES.classifications[item.classification]; pdf.text(pdf.splitTextToSize(`${item.date} | ${item.description.slice(0, 35)} | ${maskAccount(item.account)} | ${formatCurrencyBR(item.amount)} | ${classification}`, 180), margin, y); y += 6; }); }
  if (y > 250) { pdf.addPage(); y = 15; } y += 5; pdf.setFontSize(8); pdf.setTextColor(71, 85, 105); pdf.text(pdf.splitTextToSize(`Observações: ${form.analystNotes || "Sem observações."}`, 180), margin, y); y += 12; pdf.text(pdf.splitTextToSize("A apuração é uma ferramenta de apoio. O valor final aceito depende da análise documental, da coerência das movimentações e das regras da instituição financeira.", 180), margin, y); pdf.text("GoodCredit Hub — processamento local e relatório orientativo.", margin, 290); pdf.save(`goodcredit-apuracao-${form.clientName || "renda"}.pdf`);
}
