import { ArrowDownCircle, ArrowUpCircle, Pencil } from "lucide-react";
import { useMemo, useState } from "react";
import { REGISTRATION_TRANSACTION_LABELS } from "../../lib/registration/financial/constants";
import { formatCentsBRL } from "../../lib/registration/financial/money";
import type { RegistrationFinancialCaseWithMetrics, RegistrationFinancialTransaction, RegistrationFinancialTransactionInput, RegistrationFinancialTransactionType } from "../../types/registrationFinancial";
import { FinancialTransactionForm } from "./FinancialTransactionForm";

export function CashFlowTab({ records, transactions, onCreate, onUpdate }: {
  records:RegistrationFinancialCaseWithMetrics[]; transactions:RegistrationFinancialTransaction[];
  onCreate:(caseId:string,input:RegistrationFinancialTransactionInput)=>Promise<void>; onUpdate:(id:string,input:RegistrationFinancialTransactionInput)=>Promise<void>;
}) {
  const [composer,setComposer]=useState<"INCOME"|"EXPENSE"|null>(null); const [caseId,setCaseId]=useState(records.find(r=>!r.financialCase.archivedAt)?.financialCase.id??""); const [editing,setEditing]=useState<RegistrationFinancialTransaction|null>(null);
  const [start,setStart]=useState("");const [end,setEnd]=useState("");const [client,setClient]=useState("");const [process,setProcess]=useState("");const [type,setType]=useState<"ALL"|RegistrationFinancialTransactionType>("ALL");const [category,setCategory]=useState("");const [method,setMethod]=useState("");
  const cases=new Map(records.map(record=>[record.financialCase.id,record.financialCase]));
  const filtered=useMemo(()=>transactions.filter(item=>{const c=cases.get(item.caseId);const processText=`${c?.controlNumber??""} ${c?.processReference??""}`.toLocaleLowerCase("pt-BR");return(!start||item.transactionDate>=start)&&(!end||item.transactionDate<=end)&&(!client||c?.clientName.toLocaleLowerCase("pt-BR").includes(client.toLocaleLowerCase("pt-BR")))&&(!process||processText.includes(process.toLocaleLowerCase("pt-BR")))&&(type==="ALL"||item.transactionType===type)&&(!category||item.category.toLocaleLowerCase("pt-BR").includes(category.toLocaleLowerCase("pt-BR")))&&(!method||item.paymentMethod.toLocaleLowerCase("pt-BR").includes(method.toLocaleLowerCase("pt-BR")));}),[transactions,start,end,client,process,type,category,method,records]);
  const selected=records.find(record=>record.financialCase.id===caseId);
  return <section role="tabpanel" className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-950">Entradas e Saídas</h2><p className="mt-1 text-sm text-slate-600">Registre e consulte o fluxo financeiro dos seus processos.</p></div><div className="flex gap-2"><button onClick={()=>{setComposer("INCOME");setEditing(null)}} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-goodgreen-600 px-4 text-sm font-bold text-white"><ArrowDownCircle className="h-4 w-4"/>Registrar entrada</button><button onClick={()=>{setComposer("EXPENSE");setEditing(null)}} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold text-slate-700"><ArrowUpCircle className="h-4 w-4"/>Registrar saída</button></div></div>
    {(composer||editing)&&<div className="space-y-3"><label className="block max-w-xl text-sm font-bold text-slate-700">Processo<select value={editing?.caseId??caseId} disabled={Boolean(editing)} onChange={e=>setCaseId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="">Selecione</option>{records.filter(r=>!r.financialCase.archivedAt).map(({financialCase:item})=><option key={item.id} value={item.id}>Nº {item.controlNumber??"—"} · {item.clientName}</option>)}</select></label>{selected||editing?<FinancialTransactionForm operationMode={(editing?cases.get(editing.caseId):selected?.financialCase)?.operationMode??"FULL_PAYMENT_TO_GOODCREDIT"} editing={editing} disabled={false} initialType={composer??editing?.transactionType??"INCOME"} onCancelEdit={()=>{setEditing(null);setComposer(null)}} onSubmit={async input=>{const target=editing?.caseId??caseId;if(!target)throw new Error("Selecione o processo.");if(editing)await onUpdate(editing.id,input);else await onCreate(target,input);setEditing(null);setComposer(null)}}/>:<p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Selecione um processo para continuar.</p>}</div>}
    <div className="grid gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-7"><Field label="De" type="date" value={start} onChange={setStart}/><Field label="Até" type="date" value={end} onChange={setEnd}/><Field label="Cliente" value={client} onChange={setClient}/><Field label="Processo" value={process} onChange={setProcess}/><label className="text-xs font-bold text-slate-600">Tipo<select value={type} onChange={e=>setType(e.target.value as typeof type)} className="mt-1 h-10 w-full rounded-lg border border-slate-300 px-2 text-sm"><option value="ALL">Todos</option>{Object.entries(REGISTRATION_TRANSACTION_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><Field label="Categoria" value={category} onChange={setCategory}/><Field label="Forma de pagamento" value={method} onChange={setMethod}/></div>
    {filtered.length===0?<div className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Nenhuma entrada ou saída registrada no período.</div>:<div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Data","Cliente","Processo","Tipo","Categoria","Valor operacional","Juros","Pagamento","Observação","Ações"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(item=>{const c=cases.get(item.caseId);return <tr key={item.id}><td className="px-3 py-3">{new Date(`${item.transactionDate}T12:00:00`).toLocaleDateString("pt-BR")}</td><td className="px-3 py-3 font-bold">{c?.clientName??"—"}</td><td className="px-3 py-3">{c?.processReference||`Nº ${c?.controlNumber??"—"}`}</td><td className="px-3 py-3">{REGISTRATION_TRANSACTION_LABELS[item.transactionType]}</td><td className="px-3 py-3">{item.category||"—"}</td><td className="px-3 py-3 font-bold">{formatCentsBRL(item.amountCents)}</td><td className="px-3 py-3">{formatCentsBRL(item.customerInterestCents)}</td><td className="px-3 py-3">{item.paymentMethod||"—"}</td><td className="max-w-xs px-3 py-3 text-slate-600">{item.notes||item.description||"—"}</td><td className="px-3 py-3"><button onClick={()=>{setEditing(item);setComposer(null);setCaseId(item.caseId)}} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Editar lançamento"><Pencil className="h-4 w-4"/></button></td></tr>})}</tbody></table></div>}
  </section>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-xs font-bold text-slate-600">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"/></label>}
