import { Download, FileDown } from "lucide-react";
import { useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuth } from "../../contexts/AuthContext";
import { REGISTRATION_FINANCIAL_STATUS_LABELS } from "../../lib/registration/financial/constants";
import { calculateCashFlowReport } from "../../lib/registration/financial/operationalReport";
import { formatCentsBRL } from "../../lib/registration/financial/money";
import { downloadFinancialReportCsv, generateFinancialReportPdf } from "../../lib/registration/financial/reportExport";
import { COLLECTION_STATUS_LABELS, IQ_STATUS_LABELS, PAYMENT_STATUS_LABELS } from "../../lib/registration/financial/operationalConstants";
import type { RegistrationFinancialCaseWithMetrics, RegistrationFinancialReportFilters, RegistrationFinancialTransaction } from "../../types/registrationFinancial";

function monthRange(offset=0){const now=new Date();const start=new Date(now.getFullYear(),now.getMonth()+offset,1);const end=new Date(now.getFullYear(),now.getMonth()+offset+1,0);const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;return{startDate:iso(start),endDate:iso(end)}}
const current=monthRange();
const INITIAL:RegistrationFinancialReportFilters={...current,clientSearch:"",processSearch:"",operationMode:"ALL",registryOffice:"",iqStatus:"ALL",paymentStatus:"ALL",collectionStatus:"ALL",archive:"ACTIVE"};

export function FinancialReportTab({records,transactions}:{records:RegistrationFinancialCaseWithMetrics[];transactions:RegistrationFinancialTransaction[]}){
  const {user}=useAuth();const [filters,setFilters]=useState(INITIAL);const [processSort,setProcessSort]=useState("PENDING_DESC");
  const report=useMemo(()=>calculateCashFlowReport(records,transactions,filters),[records,transactions,filters]);
  const processes=useMemo(()=>[...report.processes].sort((a,b)=>processSort==="CLIENT"?a.clientName.localeCompare(b.clientName,"pt-BR"):processSort==="INCOME_DESC"?b.receivedCents-a.receivedCents:processSort==="EXPENSE_DESC"?b.paidCents-a.paidCents:processSort==="BALANCE_DESC"?b.balanceCents-a.balanceCents:b.pendingReceivableCents-a.pendingReceivableCents),[report.processes,processSort]);
  function patch(value:Partial<RegistrationFinancialReportFilters>){setFilters(f=>({...f,...value}))}function shortcut(kind:string){const now=new Date();const iso=(d:Date)=>d.toISOString().slice(0,10);if(kind==="TODAY")patch({startDate:iso(now),endDate:iso(now)});if(kind==="MONTH")patch(monthRange());if(kind==="PREVIOUS")patch(monthRange(-1));if(kind==="3MONTHS"){const start=new Date(now.getFullYear(),now.getMonth()-2,1);patch({startDate:iso(start),endDate:iso(now)})}if(kind==="YEAR")patch({startDate:`${now.getFullYear()}-01-01`,endDate:`${now.getFullYear()}-12-31`})}
  const chart=report.monthly.map(item=>({month:item.competence,Entradas:item.incomeCents/100,Saídas:(item.expensesCents+item.refundsCents)/100,Saldo:item.cumulativeBalanceCents/100}));
  const health=report.healthStatus==="HEALTHY"?"Saudável":report.healthStatus==="ATTENTION"?"Atenção":"Crítico";
  return <section role="tabpanel" className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-950">Relatório Financeiro</h2><p className="mt-1 text-sm text-slate-600">Acompanhe entradas, saídas, saldos e pendências dos seus processos.</p></div><div className="flex gap-2"><button onClick={()=>generateFinancialReportPdf(report,filters,user?.email??"Usuário autenticado")} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-sky-200 bg-sky-50 px-3 text-sm font-bold text-sky-800"><FileDown className="h-4 w-4"/>Exportar PDF</button><button onClick={()=>downloadFinancialReportCsv(report,filters)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-sm font-bold"><Download className="h-4 w-4"/>Exportar CSV</button></div></div>
    <div className="rounded-lg border border-slate-200 bg-white p-4"><div className="mb-4 flex flex-wrap gap-2">{[["TODAY","Hoje"],["MONTH","Este mês"],["PREVIOUS","Mês anterior"],["3MONTHS","Últimos 3 meses"],["YEAR","Ano atual"]].map(([id,label])=><button key={id} onClick={()=>shortcut(id)} className="rounded-full border border-slate-300 px-3 py-1.5 text-xs font-bold text-slate-600 hover:bg-slate-50">{label}</button>)}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Field label="Início" type="date" value={filters.startDate} onChange={v=>patch({startDate:v})}/><Field label="Fim" type="date" value={filters.endDate} onChange={v=>patch({endDate:v})}/><Field label="Cliente" value={filters.clientSearch} onChange={v=>patch({clientSearch:v})}/><Field label="Processo" value={filters.processSearch} onChange={v=>patch({processSearch:v})}/><Field label="Cartório" value={filters.registryOffice} onChange={v=>patch({registryOffice:v})}/><Select label="Modalidade" value={filters.operationMode} onChange={v=>patch({operationMode:v as typeof filters.operationMode})} options={{ALL:"Todas",FULL_PAYMENT_TO_GOODCREDIT:"Pagamento total",ADVISORY_ONLY:"Somente assessoria"}}/><Select label="Banco/IQ" value={filters.iqStatus} onChange={v=>patch({iqStatus:v as typeof filters.iqStatus})} options={{ALL:"Todos",...IQ_STATUS_LABELS}}/><Select label="Status pagamento" value={filters.paymentStatus} onChange={v=>patch({paymentStatus:v as typeof filters.paymentStatus})} options={{ALL:"Todos",...PAYMENT_STATUS_LABELS}}/><Select label="Cobrança" value={filters.collectionStatus} onChange={v=>patch({collectionStatus:v as typeof filters.collectionStatus})} options={{ALL:"Todas",...COLLECTION_STATUS_LABELS}}/><Select label="Registros" value={filters.archive} onChange={v=>patch({archive:v as typeof filters.archive})} options={{ACTIVE:"Ativos",ARCHIVED:"Arquivados",ALL:"Todos"}}/></div></div>
    {report.monthly.length===0?<div className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Não existem movimentações financeiras para o período selecionado.</div>:<>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{[["Entradas líquidas",report.netIncomeCents],["Saídas operacionais",report.operationalExpensesCents],["Saldo líquido",report.netBalanceCents],["Assessoria recebida",report.advisoryReceivedCents],["Recursos para custas",report.costFundsReceivedCents],["ITBI pago",report.itbiPaidCents],["Custas pagas",report.registryFeesPaidCents],["Pagamentos diretos",report.directCustomerPaymentsCents],["Juros informativos",report.customerInterestCents],["Valores a receber",report.receivableCents],["Valores a devolver",report.refundableCents]].map(([label,value])=><Metric key={String(label)} label={String(label)} value={formatCentsBRL(Number(value))}/>)}</div>
      <div className={`rounded-lg border p-5 ${report.healthStatus==="CRITICAL"?"border-rose-200 bg-rose-50":report.healthStatus==="ATTENTION"?"border-amber-200 bg-amber-50":"border-goodgreen-200 bg-goodgreen-50"}`}><h3 className="text-lg font-bold">Visão da saúde financeira</h3><p className="mt-2 font-bold">Status: {health}</p><p className="mt-1 text-sm">{report.healthExplanation}</p><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2 xl:grid-cols-4"><p>Entradas x saídas: <strong>{report.expenseToIncomePercent===null?"Sem base":`${report.expenseToIncomePercent.toFixed(1)}%`}</strong></p><p>Pendente de pagamento: <strong>{formatCentsBRL(report.pendingPaymentCents)}</strong></p><p>Divergências: <strong>{report.divergenceCount}</strong></p><p>Conciliados: <strong>{report.reconciledCount}</strong></p></div></div>
      <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Entradas versus saídas por mês"><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v)=>formatCentsBRL(Number(v)*100)}/><Legend/><Line type="monotone" dataKey="Entradas" stroke="#15803d" strokeWidth={2}/><Line type="monotone" dataKey="Saídas" stroke="#dc2626" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Evolução do saldo líquido"><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v)=>formatCentsBRL(Number(v)*100)}/><Legend/><Line type="monotone" dataKey="Saldo" stroke="#0369a1" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartCard></div>
      <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="font-bold">Tabela acessível dos gráficos</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="py-2">Mês</th><th>Entradas</th><th>Saídas</th><th>Saldo</th><th>Saldo acumulado</th></tr></thead><tbody>{report.monthly.map(item=><tr key={item.competence} className="border-b border-slate-100"><td className="py-2 font-bold">{item.competence}</td><td>{formatCentsBRL(item.incomeCents)}</td><td>{formatCentsBRL(item.expensesCents+item.refundsCents)}</td><td>{formatCentsBRL(item.netBalanceCents)}</td><td>{formatCentsBRL(item.cumulativeBalanceCents)}</td></tr>)}</tbody></table></div></section>
      <div className="grid gap-5 xl:grid-cols-2"><SummaryTable title="Resumo por categoria" headers={["Categoria","Entradas","Saídas","Saldo"]} rows={report.categories.map(i=>[i.category,formatCentsBRL(i.incomeCents),formatCentsBRL(i.expenseCents),formatCentsBRL(i.balanceCents)])}/><section className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">Resumo por processo</h3><select value={processSort} onChange={e=>setProcessSort(e.target.value)} className="h-9 rounded-lg border px-2 text-xs"><option value="PENDING_DESC">Maior pendência</option><option value="INCOME_DESC">Maior entrada</option><option value="EXPENSE_DESC">Maior saída</option><option value="BALANCE_DESC">Maior saldo</option><option value="CLIENT">Cliente</option></select></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="py-2">Cliente</th><th>Recebido</th><th>Pago</th><th>Saldo</th><th>Pendente</th><th>Devolver</th><th>Situação</th></tr></thead><tbody>{processes.map(i=><tr key={i.caseId} className="border-b border-slate-100"><td className="py-2 font-bold">{i.clientName}<span className="block text-xs font-normal text-slate-400">{i.processReference}</span></td><td>{formatCentsBRL(i.receivedCents)}</td><td>{formatCentsBRL(i.paidCents)}</td><td>{formatCentsBRL(i.balanceCents)}</td><td>{formatCentsBRL(i.pendingReceivableCents)}</td><td>{formatCentsBRL(i.refundableCents)}</td><td>{REGISTRATION_FINANCIAL_STATUS_LABELS[i.status]}</td></tr>)}</tbody></table></div></section></div>
    </>}
  </section>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-xs font-bold text-slate-600">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="text-xs font-bold text-slate-600">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-300 px-2 text-sm">{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function ChartCard({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="mb-4 font-bold">{title}</h3>{children}</section>}
function SummaryTable({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="font-bold">{title}</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500">{headers.map(h=><th key={h} className="py-2">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-b border-slate-100">{row.map((v,j)=><td key={j} className={`py-2 ${j===0?"font-bold":""}`}>{v}</td>)}</tr>)}</tbody></table></div></section>}
