import { X } from "lucide-react";
import { useState } from "react";
import { FinancialMoneyInput } from "./FinancialMoneyInput";

export interface OperationalPaymentRequest { caseId: string; clientName: string; target: "ITBI" | "REGISTRY_FEES"; payer: "GOODCREDIT" | "CLIENT"; suggestedAmountCents: number; }

export function OperationalPaymentDialog({ request, onClose, onConfirm }: { request: OperationalPaymentRequest; onClose: () => void; onConfirm: (value: { amountCents: number; date: string; paymentMethod: string; reference: string; notes: string }) => Promise<void> }) {
  const [amountCents,setAmount]=useState(request.suggestedAmountCents); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [paymentMethod,setMethod]=useState(""); const [reference,setReference]=useState(""); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  async function submit(){ if(amountCents<=0){setError("Informe o valor do pagamento.");return;} setSaving(true);try{await onConfirm({amountCents,date,paymentMethod,reference,notes});onClose();}catch(e){setError(e instanceof Error?e.message:"Não foi possível registrar o pagamento.");}finally{setSaving(false);} }
  const input="h-11 w-full rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-goodgreen-500 focus:ring-4 focus:ring-goodgreen-500/10";
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="payment-dialog-title" className="w-full max-w-lg rounded-lg bg-white p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><h2 id="payment-dialog-title" className="text-lg font-bold">Registrar pagamento de {request.target === "ITBI" ? "ITBI" : "custas cartorárias"}</h2><p className="mt-1 text-sm text-slate-500">{request.clientName} · {request.payer === "GOODCREDIT" ? "Pago pela GoodCredit" : "Pago diretamente pelo cliente"}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Fechar"><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Valor<div className="mt-2"><FinancialMoneyInput valueCents={amountCents} onChange={setAmount}/></div></label><label className="text-sm font-semibold">Data<input type="date" value={date} onChange={e=>setDate(e.target.value)} className={`${input} mt-2`}/></label><label className="text-sm font-semibold">Forma de pagamento<input value={paymentMethod} onChange={e=>setMethod(e.target.value)} className={`${input} mt-2`}/></label><label className="text-sm font-semibold">Referência<input value={reference} onChange={e=>setReference(e.target.value)} className={`${input} mt-2`}/></label><label className="text-sm font-semibold sm:col-span-2">Observação<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 min-h-20 w-full rounded-lg border border-slate-300 p-3 text-sm"/></label></div>{error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-bold">Cancelar</button><button onClick={()=>void submit()} disabled={saving} className="rounded-lg bg-goodgreen-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?"Salvando...":"Registrar pagamento"}</button></div></div></div>;
}
