import { useCallback, useEffect, useState } from "react";
import { Archive, Download, FilePlus2, FolderOpen, RefreshCw, RotateCcw } from "lucide-react";
import { downloadRegistrationFinancialCsv } from "../lib/registration/financial/csv";
import { REGISTRATION_FINANCIAL_MODE_LABELS, REGISTRATION_FINANCIAL_STATUS_LABELS } from "../lib/registration/financial/constants";
import { formatCentsBRL } from "../lib/registration/financial/money";
import { navigateRegistration, registrationFinancialEditorPath } from "../lib/registration/financial/navigation";
import { archiveFinancialCase, getMyFinancialDashboard, listMyFinancialCases, listMyFinancialCasesForExport, restoreFinancialCase } from "../services/registrationFinancialService";
import type { RegistrationFinancialCaseWithMetrics, RegistrationFinancialDashboard, RegistrationFinancialListFilters } from "../types/registrationFinancial";

const INITIAL_FILTERS: RegistrationFinancialListFilters = { search: "", operationMode: "ALL", status: "ALL", archive: "ACTIVE", sort: "UPDATED_DESC", page: 1, pageSize: 10 };
const EMPTY_DASHBOARD: RegistrationFinancialDashboard = { activeCases: 0, pendingAdvisoryCents: 0, availableBalanceCents: 0, complementRequiredCents: 0, valueToRefundCents: 0 };

export function RegistrationFinancialListPage() {
  const [filters, setFilters] = useState(INITIAL_FILTERS);
  const [records, setRecords] = useState<RegistrationFinancialCaseWithMetrics[]>([]);
  const [dashboard, setDashboard] = useState(EMPTY_DASHBOARD);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setMessage("");
    try { const [list, summary] = await Promise.all([listMyFinancialCases(filters), getMyFinancialDashboard()]); setRecords(list.records); setTotal(list.total); setDashboard(summary); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível carregar os balancetes."); }
    finally { setLoading(false); }
  }, [filters]);
  useEffect(() => { void load(); }, [load]);
  function update(patch: Partial<RegistrationFinancialListFilters>) { setFilters((current) => ({ ...current, ...patch, page: patch.page ?? 1 })); }
  async function toggleArchive(record: RegistrationFinancialCaseWithMetrics) {
    const archived = Boolean(record.financialCase.archivedAt);
    if (!archived && !window.confirm("Deseja arquivar este balancete? O histórico será preservado.")) return;
    try { if (archived) await restoreFinancialCase(record.financialCase.id); else await archiveFinancialCase(record.financialCase.id); await load(); }
    catch { setMessage("Não foi possível atualizar o arquivamento."); }
  }
  async function exportCsv() {
    setMessage("");
    try { const filteredRecords = await listMyFinancialCasesForExport(filters); downloadRegistrationFinancialCsv(filteredRecords); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível exportar os balancetes."); }
  }
  const pages = Math.max(1, Math.ceil(total / filters.pageSize));
  const fieldClass = "h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-goodgreen-500 focus:ring-4 focus:ring-goodgreen-500/10";
  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-950">Balancetes Cartoriais</h2><p className="mt-1 text-sm text-slate-600">Controle por processo dos valores de assessoria, custas, despesas e devoluções.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void load()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-sm font-bold text-slate-700"><RefreshCw className="h-4 w-4" />Atualizar</button><button type="button" onClick={() => void exportCsv()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-sky-200 bg-sky-50 px-3 text-sm font-bold text-sky-800"><Download className="h-4 w-4" />Exportar CSV</button><button type="button" onClick={() => navigateRegistration("/registro/balancete/novo")} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-goodgreen-600 px-4 text-sm font-bold text-white"><FilePlus2 className="h-4 w-4" />Novo balancete</button></div></div>
      {message && <div role="alert" className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{message}</div>}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Resumo dos balancetes"><Metric label="Processos ativos" value={String(dashboard.activeCases)} /><Metric label="Assessoria pendente" value={formatCentsBRL(dashboard.pendingAdvisoryCents)} /><Metric label="Saldo disponível" value={formatCentsBRL(dashboard.availableBalanceCents)} /><Metric label="Complemento necessário" value={formatCentsBRL(dashboard.complementRequiredCents)} /><Metric label="Valor a devolver" value={formatCentsBRL(dashboard.valueToRefundCents)} /></section>
      <section className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="text-xs font-bold text-slate-600 xl:col-span-2">Pesquisar<input className={`${fieldClass} mt-1 w-full`} value={filters.search} onChange={(e) => update({ search: e.target.value })} placeholder="Cliente, processo, cartório ou cidade" /></label><label className="text-xs font-bold text-slate-600">Modalidade<select className={`${fieldClass} mt-1 w-full`} value={filters.operationMode} onChange={(e) => update({ operationMode: e.target.value as RegistrationFinancialListFilters["operationMode"] })}><option value="ALL">Todas</option><option value="FULL_PAYMENT_TO_GOODCREDIT">Pagamento total</option><option value="ADVISORY_ONLY">Somente assessoria</option></select></label><label className="text-xs font-bold text-slate-600">Status<select className={`${fieldClass} mt-1 w-full`} value={filters.status} onChange={(e) => update({ status: e.target.value as RegistrationFinancialListFilters["status"] })}><option value="ALL">Todos</option>{Object.entries(REGISTRATION_FINANCIAL_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Situação<select className={`${fieldClass} mt-1 w-full`} value={filters.archive} onChange={(e) => update({ archive: e.target.value as RegistrationFinancialListFilters["archive"] })}><option value="ACTIVE">Ativos</option><option value="ARCHIVED">Arquivados</option><option value="ALL">Todos</option></select></label><label className="text-xs font-bold text-slate-600">Ordenação<select className={`${fieldClass} mt-1 w-full`} value={filters.sort} onChange={(e) => update({ sort: e.target.value as RegistrationFinancialListFilters["sort"] })}><option value="UPDATED_DESC">Atualizados recentemente</option><option value="UPDATED_ASC">Atualizados há mais tempo</option><option value="CLIENT_ASC">Cliente A-Z</option><option value="OPENED_DESC">Abertura mais recente</option></select></label></div></section>
      {loading ? <div className="rounded-lg border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Carregando balancetes...</div> : records.length === 0 ? <div className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-bold text-slate-800">Nenhum balancete encontrado</p><p className="mt-1 text-sm text-slate-500">Crie um novo registro ou ajuste os filtros.</p></div> : <><div className="hidden overflow-x-auto rounded-lg border border-slate-200 bg-white shadow-sm md:block"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Cliente", "Processo", "Modalidade", "Status", "Assessoria pendente", "Saldo", "Atualizado", "Ações"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{records.map((record) => <RecordRow key={record.financialCase.id} record={record} onOpen={() => navigateRegistration(registrationFinancialEditorPath(record.financialCase.id))} onArchive={() => void toggleArchive(record)} />)}</tbody></table></div><div className="grid gap-3 md:hidden">{records.map((record) => <RecordCard key={record.financialCase.id} record={record} onOpen={() => navigateRegistration(registrationFinancialEditorPath(record.financialCase.id))} onArchive={() => void toggleArchive(record)} />)}</div></>}
      <div className="flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600"><label>Itens por página <select className="ml-2 rounded-lg border border-slate-300 px-2 py-1" value={filters.pageSize} onChange={(e) => update({ pageSize: Number(e.target.value) as 10 | 25 | 50 })}><option>10</option><option>25</option><option>50</option></select></label><div className="flex items-center gap-2"><button className="rounded-lg border px-3 py-1.5 disabled:opacity-40" disabled={filters.page <= 1} onClick={() => update({ page: filters.page - 1 })}>Anterior</button><span>Página {filters.page} de {pages}</span><button className="rounded-lg border px-3 py-1.5 disabled:opacity-40" disabled={filters.page >= pages} onClick={() => update({ page: filters.page + 1 })}>Próxima</button></div></div>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-lg font-bold text-slate-950">{value}</p></div>; }
function RecordRow({ record, onOpen, onArchive }: { record: RegistrationFinancialCaseWithMetrics; onOpen: () => void; onArchive: () => void }) { const { financialCase: item, metrics } = record; return <tr><td className="px-4 py-3 font-bold text-slate-900">{item.clientName}</td><td className="px-4 py-3 text-slate-600">{item.processReference || "—"}</td><td className="px-4 py-3">{REGISTRATION_FINANCIAL_MODE_LABELS[item.operationMode]}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{REGISTRATION_FINANCIAL_STATUS_LABELS[metrics.status]}</span></td><td className="px-4 py-3 font-semibold">{formatCentsBRL(metrics.advisoryPendingCents)}</td><td className="px-4 py-3 font-semibold">{formatCentsBRL(metrics.costBalanceCents)}</td><td className="px-4 py-3 text-slate-500">{new Date(item.updatedAt).toLocaleDateString("pt-BR")}</td><td className="px-4 py-3"><div className="flex gap-1"><button onClick={onOpen} className="rounded-lg p-2 text-sky-700 hover:bg-sky-50" aria-label="Abrir balancete"><FolderOpen className="h-4 w-4" /></button><button onClick={onArchive} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100" aria-label={item.archivedAt ? "Restaurar balancete" : "Arquivar balancete"}>{item.archivedAt ? <RotateCcw className="h-4 w-4" /> : <Archive className="h-4 w-4" />}</button></div></td></tr>; }
function RecordCard({ record, onOpen, onArchive }: { record: RegistrationFinancialCaseWithMetrics; onOpen: () => void; onArchive: () => void }) { const { financialCase: item, metrics } = record; return <article className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-slate-950">{item.clientName}</h3><p className="text-sm text-slate-500">{item.processReference || "Sem referência"}</p></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{REGISTRATION_FINANCIAL_STATUS_LABELS[metrics.status]}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Assessoria pendente</p><strong>{formatCentsBRL(metrics.advisoryPendingCents)}</strong></div><div><p className="text-xs text-slate-500">Saldo</p><strong>{formatCentsBRL(metrics.costBalanceCents)}</strong></div></div><div className="mt-4 flex gap-2"><button onClick={onOpen} className="flex-1 rounded-lg bg-goodgreen-600 px-3 py-2 text-sm font-bold text-white">Abrir</button><button onClick={onArchive} className="rounded-lg border border-slate-300 p-2 text-slate-600">{item.archivedAt ? <RotateCcw className="h-4 w-4" /> : <Archive className="h-4 w-4" />}</button></div></article>; }
