import { useEffect, useMemo, useState } from "react";
import { Archive, ArrowLeft, ChevronRight, FileDown, LockKeyhole, RotateCcw, Save } from "lucide-react";
import { FinancialMoneyInput } from "../components/registration-financial/FinancialMoneyInput";
import { FinancialSummary } from "../components/registration-financial/FinancialSummary";
import { FinancialTimeline } from "../components/registration-financial/FinancialTimeline";
import { FinancialTransactionForm } from "../components/registration-financial/FinancialTransactionForm";
import { OperationalPaymentDialog, type OperationalPaymentRequest } from "../components/registration-financial/OperationalPaymentDialog";
import { calculateRegistrationFinancialMetrics } from "../lib/registration/financial/calculations";
import { DEFAULT_REGISTRATION_ADVISORY_FEE_CENTS, REGISTRATION_FINANCIAL_MODE_LABELS } from "../lib/registration/financial/constants";
import { navigateRegistration, registrationFinancialEditorPath } from "../lib/registration/financial/navigation";
import { generateRegistrationFinancialPdf } from "../lib/registration/financial/pdf";
import { COLLECTION_STATUS_LABELS, IQ_STATUS_LABELS, ITBI_PAYMENT_STATUS_LABELS, PAYMENT_STATUS_LABELS, REGISTRY_COSTS_PAYMENT_STATUS_LABELS, SELLER_PAYMENT_STATUS_LABELS } from "../lib/registration/financial/operationalConstants";
import { validateRegistrationFinancialCase } from "../lib/registration/financial/validation";
import { archiveFinancialCase, createFinancialCase, createFinancialTransaction, finalizeFinancialCase, getMyFinancialCaseById, listRegistrationOperationalSuggestions, registerOperationalPayment, reopenFinancialCase, restoreFinancialCase, updateFinancialCase, updateFinancialTransaction } from "../services/registrationFinancialService";
import type { RegistrationFinancialCase, RegistrationFinancialCaseInput, RegistrationFinancialTransaction, RegistrationFinancialTransactionInput } from "../types/registrationFinancial";

function today(){return new Date().toISOString().slice(0,10)}
const BLANK:RegistrationFinancialCaseInput={clientName:"",processReference:"",registryOffice:"",city:"",signingDate:null,referralSource:"",bankBranch:"",iqStatus:null,paymentStatus:null,collectionStatus:null,itbiAmountCents:0,itbiPaymentStatus:"PENDING",protocolReference:"",registryCostsCents:0,registryCostsPaymentStatus:"PENDING",operationalStatus:"",bankDeliveryDate:null,sellerPaymentStatus:"PENDING",sellerPaymentDate:null,operationMode:"FULL_PAYMENT_TO_GOODCREDIT",advisoryFeeExpectedCents:DEFAULT_REGISTRATION_ADVISORY_FEE_CENTS,estimatedItbiCents:0,estimatedRegistryCents:0,estimatedOtherCostsCents:0,notes:"",openedAt:today()};
function toInput(item:RegistrationFinancialCase):RegistrationFinancialCaseInput{return{clientName:item.clientName,processReference:item.processReference,registryOffice:item.registryOffice,city:item.city,signingDate:item.signingDate,referralSource:item.referralSource,bankBranch:item.bankBranch,iqStatus:item.iqStatus,paymentStatus:item.paymentStatus,collectionStatus:item.collectionStatus,itbiAmountCents:item.itbiAmountCents,itbiPaymentStatus:item.itbiPaymentStatus,protocolReference:item.protocolReference,registryCostsCents:item.registryCostsCents,registryCostsPaymentStatus:item.registryCostsPaymentStatus,operationalStatus:item.operationalStatus,bankDeliveryDate:item.bankDeliveryDate,sellerPaymentStatus:item.sellerPaymentStatus,sellerPaymentDate:item.sellerPaymentDate,operationMode:item.operationMode,advisoryFeeExpectedCents:item.advisoryFeeExpectedCents,estimatedItbiCents:item.estimatedItbiCents,estimatedRegistryCents:item.estimatedRegistryCents,estimatedOtherCostsCents:item.estimatedOtherCostsCents,notes:item.notes,openedAt:item.openedAt}}

export function RegistrationFinancialEditorPage({caseId}:{caseId:string|null}){
  const [input,setInput]=useState(BLANK);const [record,setRecord]=useState<RegistrationFinancialCase|null>(null);const [transactions,setTransactions]=useState<RegistrationFinancialTransaction[]>([]);const [editing,setEditing]=useState<RegistrationFinancialTransaction|null>(null);const [step,setStep]=useState(1);const [feeUnlocked,setFeeUnlocked]=useState(false);const [loading,setLoading]=useState(Boolean(caseId));const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [paymentRequest,setPaymentRequest]=useState<OperationalPaymentRequest|null>(null);const [suggestions,setSuggestions]=useState({referrals:[] as string[],bankBranches:[] as string[],registryOffices:[] as string[]});
  const metrics=useMemo(()=>calculateRegistrationFinancialMetrics(record??({...input,id:"new",ownerId:"",controlNumber:null,operationalStatusUpdatedAt:null,financialFinalizedAt:null,archivedAt:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()} satisfies RegistrationFinancialCase),transactions),[record,input,transactions]);const locked=Boolean(record?.archivedAt||record?.financialFinalizedAt);
  async function load(id=caseId){if(!id)return;setLoading(true);try{const detail=await getMyFinancialCaseById(id);setRecord(detail.financialCase);setInput(toInput(detail.financialCase));setTransactions(detail.transactions);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível carregar o processo.");}finally{setLoading(false)}}
  useEffect(()=>{void load();void listRegistrationOperationalSuggestions().then(setSuggestions).catch(()=>undefined)},[caseId]);
  function set<K extends keyof RegistrationFinancialCaseInput>(key:K,value:RegistrationFinancialCaseInput[K]){setInput(current=>({...current,[key]:value}))}
  function setPaymentStatus(value:RegistrationFinancialCaseInput["paymentStatus"]){const expected=value==="FULL_PAYMENT"?"FULL_PAYMENT_TO_GOODCREDIT":value==="ADVISORY_ONLY"?"ADVISORY_ONLY":null;if(expected&&expected!==input.operationMode&&window.confirm("O status de pagamento selecionado não corresponde à modalidade atual do balancete. Deseja atualizar a modalidade?"))setInput(current=>({...current,paymentStatus:value,operationMode:expected}));else set("paymentStatus",value)}
  function selectOperationalPayment(target:"ITBI"|"REGISTRY_FEES",status:string){if(status==="PAID_BY_GOODCREDIT"||status==="PAID_BY_CLIENT"){if(!caseId){setMessage("Crie o processo antes de registrar o pagamento e a movimentação financeira correspondente.");return;}setPaymentRequest({caseId,clientName:input.clientName,target,payer:status==="PAID_BY_GOODCREDIT"?"GOODCREDIT":"CLIENT",suggestedAmountCents:target==="ITBI"?input.itbiAmountCents:input.registryCostsCents});return;}if(target==="ITBI")set("itbiPaymentStatus",status as RegistrationFinancialCaseInput["itbiPaymentStatus"]);else set("registryCostsPaymentStatus",status as RegistrationFinancialCaseInput["registryCostsPaymentStatus"])}
  async function save(){const errors=validateRegistrationFinancialCase(input);if(errors.length){setMessage(errors.join(" "));return}setSaving(true);try{if(!caseId){const id=await createFinancialCase(input);navigateRegistration(registrationFinancialEditorPath(id),true)}else{await updateFinancialCase(caseId,input);await load(caseId);setMessage("Processo salvo.")}}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível salvar o processo.")}finally{setSaving(false)}}
  async function submitTransaction(value:RegistrationFinancialTransactionInput){if(!caseId)throw new Error("Salve o processo antes.");if(editing)await updateFinancialTransaction(editing.id,value);else await createFinancialTransaction(caseId,value);setEditing(null);await load(caseId)}
  async function toggleFinalized(){if(!caseId||!record)return;const reopening=Boolean(record.financialFinalizedAt);if(!window.confirm(reopening?"Deseja reabrir este processo?":"Deseja finalizar a conciliação financeira?"))return;if(reopening)await reopenFinancialCase(caseId);else await finalizeFinancialCase(caseId);await load(caseId)}
  async function toggleArchived(){if(!caseId||!record)return;const restoring=Boolean(record.archivedAt);if(!restoring&&!window.confirm("Deseja arquivar este processo?"))return;if(restoring)await restoreFinancialCase(caseId);else await archiveFinancialCase(caseId);await load(caseId)}
  async function confirmPayment(value:{amountCents:number;date:string;paymentMethod:string;reference:string;notes:string}){if(!paymentRequest)return;await registerOperationalPayment({...paymentRequest,...value});await load(caseId);}
  if(loading)return <div className="rounded-lg border bg-white p-10 text-center text-sm text-slate-500">Carregando processo...</div>;
  const inputClass="mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-goodgreen-500 focus:ring-4 focus:ring-goodgreen-500/10 disabled:bg-slate-100";
  const identification=<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Text label="Cliente *" value={input.clientName} onChange={v=>set("clientName",v)} disabled={locked}/><Text label="Referência do processo" value={input.processReference} onChange={v=>set("processReference",v)} disabled={locked}/><Field label="Data de assinatura"><input type="date" value={input.signingDate??""} onChange={e=>set("signingDate",e.target.value||null)} disabled={locked} className={inputClass}/></Field><Text label="Indicação" value={input.referralSource} onChange={v=>set("referralSource",v)} disabled={locked} list="referral-list"/><Text label="Agência/Banco" value={input.bankBranch} onChange={v=>set("bankBranch",v)} disabled={locked} list="bank-list"/><Select label="IQ" value={input.iqStatus??""} options={IQ_STATUS_LABELS} onChange={v=>set("iqStatus",v as RegistrationFinancialCaseInput["iqStatus"])} disabled={locked}/><Select label="Modalidade" value={input.operationMode} options={REGISTRATION_FINANCIAL_MODE_LABELS} onChange={v=>set("operationMode",v as RegistrationFinancialCaseInput["operationMode"])} disabled={locked||transactions.length>0}/><Text label="Cidade" value={input.city} onChange={v=>set("city",v)} disabled={locked}/></div>;
  const payments=<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Select label="Status de pagamento" value={input.paymentStatus??""} options={PAYMENT_STATUS_LABELS} onChange={v=>setPaymentStatus(v as RegistrationFinancialCaseInput["paymentStatus"])} disabled={locked}/><Select label="Cobrança" value={input.collectionStatus??""} options={COLLECTION_STATUS_LABELS} onChange={v=>set("collectionStatus",v as RegistrationFinancialCaseInput["collectionStatus"])} disabled={locked}/><Money label="Assessoria prevista" value={input.advisoryFeeExpectedCents} onChange={v=>set("advisoryFeeExpectedCents",v)} disabled={locked||!feeUnlocked}/>{!feeUnlocked&&!locked&&<button type="button" onClick={()=>{if(window.confirm("Deseja alterar o valor padrão da assessoria?"))setFeeUnlocked(true)}} className="self-end rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold">Alterar assessoria</button>}</div>;
  const registry=<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Money label="Valor do ITBI" value={input.itbiAmountCents} onChange={v=>set("itbiAmountCents",v)} disabled={locked}/><Select label="Pagamento do ITBI" value={input.itbiPaymentStatus??""} options={ITBI_PAYMENT_STATUS_LABELS} onChange={v=>selectOperationalPayment("ITBI",v)} disabled={locked}/><Text label="Cartório" value={input.registryOffice} onChange={v=>set("registryOffice",v)} disabled={locked} list="registry-list"/><Text label="Protocolo" value={input.protocolReference} onChange={v=>set("protocolReference",v)} disabled={locked}/><Money label="Valor das custas" value={input.registryCostsCents} onChange={v=>set("registryCostsCents",v)} disabled={locked}/><Select label="Pagamento das custas" value={input.registryCostsPaymentStatus??""} options={REGISTRY_COSTS_PAYMENT_STATUS_LABELS} onChange={v=>selectOperationalPayment("REGISTRY_FEES",v)} disabled={locked}/></div>;
  const progress=<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Status operacional"><textarea value={input.operationalStatus} onChange={e=>set("operationalStatus",e.target.value)} disabled={locked} className="mt-2 min-h-28 w-full rounded-lg border border-slate-300 p-3 text-sm"/></Field><Field label="Entrega no banco"><input type="date" value={input.bankDeliveryDate??""} onChange={e=>set("bankDeliveryDate",e.target.value||null)} disabled={locked} className={inputClass}/></Field><Select label="Pagamento ao vendedor" value={input.sellerPaymentStatus??""} options={SELLER_PAYMENT_STATUS_LABELS} onChange={v=>set("sellerPaymentStatus",v as RegistrationFinancialCaseInput["sellerPaymentStatus"])} disabled={locked}/><Field label="Data do pagamento ao vendedor"><input type="date" value={input.sellerPaymentDate??""} onChange={e=>set("sellerPaymentDate",e.target.value||null)} disabled={locked} className={inputClass}/></Field><Field label="Observações"><textarea value={input.notes} onChange={e=>set("notes",e.target.value)} disabled={locked} className="mt-2 min-h-28 w-full rounded-lg border border-slate-300 p-3 text-sm"/></Field></div>;
  return <div className="space-y-5"><datalist id="referral-list">{suggestions.referrals.map(v=><option key={v} value={v}/>)}</datalist><datalist id="bank-list">{suggestions.bankBranches.map(v=><option key={v} value={v}/>)}</datalist><datalist id="registry-list">{suggestions.registryOffices.map(v=><option key={v} value={v}/>)}</datalist>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><button onClick={()=>navigateRegistration("/registro?ferramenta=balancete&aba=processos")} className="mb-3 inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Voltar ao controle</button><h2 className="text-2xl font-bold">{caseId?`Processo Nº ${record?.controlNumber??"—"}`:"Novo processo"}</h2><p className="mt-1 text-sm text-slate-500">Balancete Cartorial · controle operacional e financeiro</p></div>{record&&<div className="flex flex-wrap gap-2"><button onClick={()=>void generateRegistrationFinancialPdf({financialCase:record,transactions,metrics})} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-sky-200 bg-sky-50 px-3 text-sm font-bold text-sky-800"><FileDown className="h-4 w-4"/>PDF</button><button onClick={()=>void toggleFinalized()} disabled={Boolean(record.archivedAt)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border px-3 text-sm font-bold disabled:opacity-40">{record.financialFinalizedAt?<RotateCcw className="h-4 w-4"/>:<LockKeyhole className="h-4 w-4"/>}{record.financialFinalizedAt?"Reabrir":"Finalizar"}</button><button onClick={()=>void toggleArchived()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border px-3 text-sm font-bold">{record.archivedAt?<RotateCcw className="h-4 w-4"/>:<Archive className="h-4 w-4"/>}{record.archivedAt?"Restaurar":"Arquivar"}</button></div>}</div>
    {message&&<div role="alert" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{message}</div>}{locked&&<div className="rounded-lg border border-sky-200 bg-sky-50 p-3 text-sm text-sky-900">Processo {record?.archivedAt?"arquivado":"finalizado"}. Reabra ou restaure para editar.</div>}
    {!caseId?<><div className="grid grid-cols-4 gap-2">{["Identificação","Pagamento","ITBI e cartório","Revisão"].map((label,index)=><div key={label} className={`rounded-lg border px-2 py-3 text-center text-xs font-bold ${step===index+1?"border-goodgreen-300 bg-goodgreen-50 text-goodgreen-800":"border-slate-200 bg-white text-slate-500"}`}>{index+1}. {label}</div>)}</div><section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="mb-5 text-lg font-bold">{step===1?"Identificação":step===2?"Situação de pagamento":step===3?"ITBI e cartório":"Revise antes de criar"}</h3>{step===1?identification:step===2?payments:step===3?registry:<div className="space-y-4">{identification}{payments}{registry}<details><summary className="cursor-pointer font-bold">Mais informações</summary><div className="mt-4">{progress}</div></details></div>}<div className="mt-6 flex justify-between"><button disabled={step===1} onClick={()=>setStep(v=>v-1)} className="rounded-lg border px-4 py-2 text-sm font-bold disabled:opacity-30">Voltar</button>{step<4?<button onClick={()=>setStep(v=>v+1)} className="inline-flex items-center gap-2 rounded-lg bg-goodgreen-600 px-4 py-2 text-sm font-bold text-white">Continuar<ChevronRight className="h-4 w-4"/></button>:<button onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-goodgreen-600 px-4 py-2 text-sm font-bold text-white"><Save className="h-4 w-4"/>{saving?"Criando...":"Criar processo"}</button>}</div></section></>:<>
      <Accordion title="1. Identificação" open>{identification}</Accordion><Accordion title="2. Pagamentos">{payments}<div className="mt-5"><FinancialSummary metrics={metrics}/></div></Accordion><Accordion title="3. Cartório e protocolo">{registry}</Accordion><Accordion title="4. Andamento">{progress}</Accordion><button onClick={()=>void save()} disabled={locked||saving} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-goodgreen-600 px-4 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?"Salvando...":"Salvar alterações"}</button>
      <details className="rounded-lg border border-slate-200 bg-white"><summary className="cursor-pointer px-5 py-4 font-bold">Movimentações financeiras ({transactions.length})</summary><div className="space-y-5 border-t p-5"><FinancialTransactionForm operationMode={input.operationMode} editing={editing} disabled={locked} onCancelEdit={()=>setEditing(null)} onSubmit={submitTransaction}/><FinancialTimeline transactions={transactions} disabled={locked} onEdit={setEditing}/></div></details>
    </>}
    {paymentRequest&&<OperationalPaymentDialog request={paymentRequest} onClose={()=>setPaymentRequest(null)} onConfirm={confirmPayment}/>}</div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-semibold text-slate-700">{label}{children}</label>}
function Text({label,value,onChange,disabled,list}:{label:string;value:string;onChange:(v:string)=>void;disabled:boolean;list?:string}){return <Field label={label}><input list={list} value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} className="mt-2 h-11 w-full rounded-lg border border-slate-300 px-3 text-sm disabled:bg-slate-100"/></Field>}
function Select({label,value,options,onChange,disabled}:{label:string;value:string;options:Record<string,string>;onChange:(v:string)=>void;disabled:boolean}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} className="mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm disabled:bg-slate-100"><option value="">Selecionar</option>{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>}
function Money({label,value,onChange,disabled}:{label:string;value:number;onChange:(v:number)=>void;disabled:boolean}){return <Field label={label}><div className="mt-2"><FinancialMoneyInput valueCents={value} onChange={onChange} disabled={disabled}/></div></Field>}
function Accordion({title,children,open=false}:{title:string;children:React.ReactNode;open?:boolean}){return <details open={open} className="rounded-lg border border-slate-200 bg-white"><summary className="cursor-pointer px-5 py-4 text-lg font-bold">{title}</summary><div className="border-t p-5">{children}</div></details>}
