import { useState } from "react";
import { FGTS_RULES } from "../../lib/fgts/fgtsRules";
import { formatCurrencyBR, parseNumberBR } from "../../lib/financial";

export function FgtsInstallmentPaymentInfo() {
  const [installment, setInstallment] = useState(0); const [count, setCount] = useState(12); const [coverage, setCoverage] = useState(80); const [balance, setBalance] = useState(0);
  const total = installment * count; const limit = total * Math.min(FGTS_RULES.maximumInstallmentCoveragePercent, coverage / 100); const fgts = Math.min(balance, limit);
  return <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-bold">Pagamento de Parte das Prestações</h2><p className="mt-2 text-sm leading-6 text-slate-600">Esta modalidade é diferente da amortização do saldo devedor e não será enviada à planilha como redução direta. A cobertura teórica é limitada a 80% e depende do agente financeiro.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-semibold">Valor da prestação<input className="mt-2 h-12 w-full rounded-lg border px-3" inputMode="decimal" value={installment || ""} onChange={(e) => setInstallment(parseNumberBR(e.target.value))} /></label><label className="text-sm font-semibold">Quantidade de prestações<input className="mt-2 h-12 w-full rounded-lg border px-3" inputMode="numeric" value={count} onChange={(e) => setCount(Math.max(1, Number(e.target.value) || 1))} /></label><label className="text-sm font-semibold">Cobertura (máx. 80%)<input className="mt-2 h-12 w-full rounded-lg border px-3" inputMode="decimal" value={coverage} onChange={(e) => setCoverage(Math.min(80, Math.max(0, Number(e.target.value) || 0)))} /></label><label className="text-sm font-semibold">Saldo disponível<input className="mt-2 h-12 w-full rounded-lg border px-3" inputMode="decimal" value={balance || ""} onChange={(e) => setBalance(parseNumberBR(e.target.value))} /></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total das prestações", total], ["Limite teórico", limit], ["FGTS necessário", fgts], ["Restante do cliente", total - fgts]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="font-bold">{formatCurrencyBR(Number(value))}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Este cálculo é meramente orientativo e não representa autorização de uso.</p></section>;
}
