import { useEffect, useMemo, useState } from "react";
import { RotateCcw } from "lucide-react";
import { evaluateFgtsEligibility } from "../../lib/fgts/eligibilityEngine";
import { buildFgtsWhatsAppMessage } from "../../lib/fgts/fgtsMessageBuilder";
import { generateFgtsPdf } from "../../lib/fgts/fgtsPdfGenerator";
import { FGTS_INSTITUTIONAL_NOTICE, FGTS_RULES } from "../../lib/fgts/fgtsRules";
import { estimateIncomeFromFgts } from "../../lib/fgts/incomeEstimator";
import { projectFgtsContributions } from "../../lib/fgts/projectionEngine";
import { FgtsAmortizationPrefill, FgtsModuleState } from "../../types/fgts";
import { FgtsAmortizationPlanner } from "./FgtsAmortizationPlanner";
import { FgtsDocumentChecklist } from "./FgtsDocumentChecklist";
import { FgtsEligibilityCard } from "./FgtsEligibilityCard";
import { FgtsIncomeEstimator } from "./FgtsIncomeEstimator";
import { FgtsInstallmentPaymentInfo } from "./FgtsInstallmentPaymentInfo";
import { FgtsOverview } from "./FgtsOverview";
import { FgtsResultPanel } from "./FgtsResultPanel";

const STATE_KEY = "goodcredit_fgts_state"; const DOC_KEY = "goodcredit_fgts_document_checklist"; const PREFILL_KEY = "goodcredit_fgts_amortization_prefill";
const initialState: FgtsModuleState = { clientName: "", eligibility: { employmentThreeYears: "UNKNOWN", activeSfhFinancing: "UNKNOWN", ownsHomeResidenceCity: "UNKNOWN", ownsHomeWorkCity: "UNKNOWN", ownsHomeNearbyCity: "UNKNOWN", ownHousingPurpose: "UNKNOWN", contractEligible: "UNKNOWN", usageMode: "", installmentsCurrent: "NOT_APPLICABLE" }, income: { payslipCompetence: "", payslipGross: 0, depositCompetence: "", monthlyDeposit: 0, employmentType: "REGULAR", contributionRate: FGTS_RULES.standardEmployeeRate, criterion: "HIGHEST", manualIncome: 0, regularMonthlyDeposit: true, sameCompetence: true, notThirteenthSalary: true, notAtypicalPayment: true, rateConfirmed: true }, projection: { contractDate: "", lastUsageDate: "", neverUsed: true, currentBalance: 0, monthlyDeposit: 0, remainingTermMonths: 360, firstContributionMonth: 24, periodicityMonths: 24, advancedPeriodicity: false, contributionMode: "FIXED", fixedAmount: 0 }, customEvents: [] };
function loadState(): FgtsModuleState { try { return { ...initialState, ...JSON.parse(localStorage.getItem(STATE_KEY) || "{}") }; } catch { return initialState; } }
function loadDocs(): Record<string, boolean> { try { return JSON.parse(localStorage.getItem(DOC_KEY) || "{}"); } catch { return {}; } }

export function FgtsPage({ onSendToAmortization }: { onSendToAmortization: () => void }) {
  const [state, setState] = useState(loadState); const [checked, setChecked] = useState(loadDocs); const [notice, setNotice] = useState("");
  const eligibility = useMemo(() => evaluateFgtsEligibility(state.eligibility), [state.eligibility]); const incomeResult = useMemo(() => estimateIncomeFromFgts(state.income), [state.income]); const generatedProjection = useMemo(() => projectFgtsContributions(state.projection), [state.projection]);
  const events = state.customEvents.length ? state.customEvents : generatedProjection.events; const projection = { ...generatedProjection, events, totalProjected: events.filter((event) => event.active).reduce((sum, event) => sum + event.amount, 0) };
  useEffect(() => { localStorage.setItem(STATE_KEY, JSON.stringify(state)); }, [state]); useEffect(() => { localStorage.setItem(DOC_KEY, JSON.stringify(checked)); }, [checked]);
  function updateProjection(next: FgtsModuleState["projection"]) { const generated = projectFgtsContributions(next); setState((current) => ({ ...current, projection: next, customEvents: generated.events })); }
  async function copySummary() { await navigator.clipboard.writeText(buildFgtsWhatsAppMessage({ clientName: state.clientName, usageMode: state.eligibility.usageMode, eligibility, incomeForm: state.income, incomeResult, projection, checkedDocuments: checked })); setNotice("Resumo copiado para a área de transferência."); }
  function send() { const prefill: FgtsAmortizationPrefill = { clientName: state.clientName, periodicityMonths: state.projection.periodicityMonths, nextEligibleDate: projection.nextEligibleDate, events: projection.events.filter((e) => e.active && e.amount > 0).map((e) => ({ month: e.month, amount: e.amount, source: "FGTS" })) }; localStorage.setItem(PREFILL_KEY, JSON.stringify(prefill)); onSendToAmortization(); }
  function clear() { if (!window.confirm("Deseja apagar a análise de FGTS salva neste navegador?")) return; localStorage.removeItem(STATE_KEY); localStorage.removeItem(DOC_KEY); setState(initialState); setChecked({}); setNotice("Análise limpa."); }
  const pdfData = { clientName: state.clientName, usageMode: state.eligibility.usageMode, eligibility, incomeForm: state.income, incomeResult, projection, checkedDocuments: checked };
  return <main className="mx-auto flex max-w-[1700px] flex-col gap-6 px-4 py-6 sm:px-6 xl:px-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-goodgreen-700">GoodCredit Hub</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Uso de FGTS</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Consulte regras, estime renda e simule a utilização do FGTS no financiamento imobiliário.</p></div><button type="button" className="btn-muted" onClick={clear}><RotateCcw className="h-4 w-4" /> Limpar Análise</button></header>{notice && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}<label className="rounded-lg border border-slate-200 bg-white p-5 text-sm font-semibold shadow-sm">Nome do cliente ou processo (opcional)<input className="mt-2 h-12 w-full rounded-lg border border-slate-300 px-3 font-normal outline-none focus:border-goodgreen-500 focus:ring-4 focus:ring-goodgreen-500/10" value={state.clientName} onChange={(e) => setState({ ...state, clientName: e.target.value })} placeholder="Identificação interna, sem dados sensíveis" /></label><FgtsOverview /><FgtsEligibilityCard form={state.eligibility} result={eligibility} onChange={(value) => setState({ ...state, eligibility: value })} /><FgtsIncomeEstimator form={state.income} result={incomeResult} onChange={(value) => setState({ ...state, income: value })} /><FgtsAmortizationPlanner form={state.projection} result={projection} events={events} onFormChange={updateProjection} onEventsChange={(customEvents) => setState({ ...state, customEvents })} /><FgtsInstallmentPaymentInfo /><FgtsDocumentChecklist checked={checked} onChange={setChecked} /><FgtsResultPanel usageMode={state.eligibility.usageMode} eligibility={eligibility} incomeForm={state.income} incomeResult={incomeResult} projection={projection} checked={checked} onCopy={copySummary} onPdf={() => generateFgtsPdf(pdfData)} onSend={send} /><div className="rounded-lg border border-goodblue-100 bg-goodblue-50 p-4 text-sm leading-6 text-goodblue-800">{FGTS_INSTITUTIONAL_NOTICE}</div></main>;
}
