import { Trash2 } from "lucide-react";
import { formatCurrencyBR } from "../../lib/financial";
import type { FgtsAmortizationEvent } from "../../types/fgts";
import { FgtsCurrencyInput } from "./FgtsCurrencyInput";

export function FgtsEventTable({ events, onChange }: { events: FgtsAmortizationEvent[]; onChange: (events: FgtsAmortizationEvent[]) => void }) {
  function update(id: string, patch: Partial<FgtsAmortizationEvent>) { onChange(events.map((event) => event.id === id ? { ...event, ...patch } : event)); }
  return <div className="mt-5 overflow-x-auto rounded-lg border border-slate-200"><table className="min-w-[950px] w-full text-sm"><thead className="bg-slate-100 text-left text-xs font-bold text-slate-600"><tr>{["Evento", "Mês", "Data estimada", "Saldo disponível", "Valor a utilizar", "Saldo remanescente", "Ativo", "Observação", ""].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{events.map((event) => <tr key={event.id}><td className="px-3 py-3 font-bold">{event.eventNumber}</td><td className="px-3 py-3 font-semibold">{event.month}</td><td className="px-3 py-3">{event.estimatedDate ? new Date(`${event.estimatedDate}T12:00:00`).toLocaleDateString("pt-BR") : "—"}</td><td className="px-3 py-3">{formatCurrencyBR(event.availableBalance)}</td><td className="px-3 py-3"><FgtsCurrencyInput ariaLabel={`Valor do evento ${event.eventNumber}`} className="h-10 w-36 rounded-md border border-slate-300 px-2" value={event.amount} onValueChange={(amount) => update(event.id, { amount })} /></td><td className="px-3 py-3">{formatCurrencyBR(Math.max(0, event.availableBalance - event.amount))}</td><td className="px-3 py-3"><input type="checkbox" checked={event.active} onChange={(changeEvent) => update(event.id, { active: changeEvent.target.checked })} /></td><td className="px-3 py-3"><input className="w-44 rounded-md border p-2" value={event.note} onChange={(changeEvent) => update(event.id, { note: changeEvent.target.value })} /></td><td className="px-3 py-3"><button type="button" className="rounded-md p-2 text-rose-600 hover:bg-rose-50" title="Excluir evento" onClick={() => onChange(events.filter((item) => item.id !== event.id))}><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>;
}
